config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  resources :users, only: [:show]
  resources :messages, only: [:create]

  resources :posts do
    member do
      get :toggle_status
    end
  end

  get 'blog', to: 'pages#blog'

  mount ActionCable.server => '/cable'
  
  root to: 'pages#home'

end

app/views/shared/_dashboard_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-transparent navbar-absolute bg-danger fixed-top">
    <div class="container-fluid">
        <div class="navbar-wrapper">
            <div class="navbar-toggle">
                <button type="button" class="navbar-toggler">
                    <span class="navbar-toggler-bar bar1"></span>
                    <span class="navbar-toggler-bar bar2"></span>
                    <span class="navbar-toggler-bar bar3"></span>
                </button>
            </div>
            <a class="navbar-brand" href="#">Dashboard</a>
        </div>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navigation" aria-controls="navigation-index" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-bar navbar-kebab"></span>
            <span class="navbar-toggler-bar navbar-kebab"></span>
            <span class="navbar-toggler-bar navbar-kebab"></span>
        </button>
        <div class="collapse navbar-collapse justify-content-end" id="navigation">
            <ul class="nav navbar-nav mr-auto">
                <li class="dropdown nav-item">
                    <a href="#" class="dropdown-toggle nav-link" data-toggle="dropdown">
                        <i class="now-ui-icons objects_planet"></i>
                        <span class="notification">5</span>
                        <span class="d-lg-none">Notifications</span>
                    </a>
                    <ul class="dropdown-menu">
                        <a class="dropdown-item" href="#">Notification 1</a>
                        <a class="dropdown-item" href="#">Notification 2</a>
                        <a class="dropdown-item" href="#">Notification 3</a>
                        <a class="dropdown-item" href="#">Notification 4</a>
                        <a class="dropdown-item" href="#">Another notification</a>
                    </ul>
                </li>
            </ul>
            <ul class="navbar-nav">
                <%= login_helper "nav-link" %>
            </ul>
        </div>
    </div>
</nav>

app/views/shared/_dashboard_sidebar.html.erb
<div class="sidebar" data-color="red">
    <div class="logo text-center">
        <%= link_to "Home", root_url, class: "simple-text" %>
    </div>
    <div class="sidebar-wrapper">
        <div class="user">
            <div class="photo">
                <%= gravatar_helper current_user %>
            </div>
            <div class="info">
                <a data-toggle="collapse" href="#collapseExample" class="collapsed">
                    <span>
                        <%= current_user.name %>
                        <b class="caret"></b>
                    </span>
                </a>
                <div class="clearfix"></div>
                <div class="collapse" id="collapseExample">
                    <ul class="nav">
                        <!-- <li>
                            <%#= link_to user_path(current_user) do %>
                                <span class="sidebar-mini-icon">MP</span>
                                <span class="sidebar-normal">My Profile</span>
                            <%# end %>
                        </li> -->
                        <li>
                            <%= link_to edit_user_registration_path do %>
                                <span class="sidebar-mini-icon">EP</span>
                                <span class="sidebar-normal">Edit Profile</span>
                            <% end %>
                        </li>
                        <!-- <li>
                            <a href="#">
                                <span class="sidebar-mini-icon">S</span>
                                <span class="sidebar-normal">Settings</span>
                            </a>
                        </li> -->
                    </ul>
                </div>
            </div>
        </div>
        <ul class="nav">
            <% if logged_in?(:site_admin) %>
              <li class="active">
                  <a data-toggle="collapse" href="#pagesExamples" aria-expanded="true">
                      <%= fa_icon("feed") %>
                      <p>Blog
                          <b class="caret"></b>
                      </p>
                  </a>
                  <div class="collapse show" id="pagesExamples">
                      <ul class="nav">
                          <li>
                              <%= link_to posts_path do %>
                                  <span class="sidebar-mini-icon"><%= fa_icon("list") %></span>
                                  <span class="sidebar-normal">All Posts</span>
                              <% end %>
                          </li>
                          <li>
                              <%= link_to new_post_path do %>
                                  <span class="sidebar-mini-icon"><%= fa_icon("plus") %></span>
                                  <span class="sidebar-normal">New Post</span>
                              <% end %>
                          </li>
                          <!-- <li>
                              <%#= link_to comments_path do %>
                                  <span class="sidebar-mini-icon">C</span>
                                  <span class="sidebar-normal">Comments</span>
                              <%# end %>
                          </li> -->
                      </ul>
                  </div>
              </li>
            <% end %>
        </ul>
    </div>
</div>

app/views/shared/_footer.html.erb
<footer class="footer">
    <div class="container">
        <div class="copyright">
            &copy; <%= Time.current.year %> Tim Pile
        </div>
    </div>
</footer>

app/views/shared/_nav.html.erb
<nav class="navbar navbar-expand-lg bg-danger fixed-top navbar-transparent" color-on-scroll="500">
  <div class="container">
      <div class="navbar-translate">
          <%= link_to "Home", root_url, class: "navbar-brand" %>
          <button class="navbar-toggler navbar-toggler" type="button" data-toggle="collapse" data-target="#navigation" aria-controls="navigation-index" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-bar bar1"></span>
              <span class="navbar-toggler-bar bar2"></span>
              <span class="navbar-toggler-bar bar3"></span>
          </button>
      </div>
      <div class="collapse navbar-collapse justify-content-end" id="navigation" data-nav-image="<%= image_path('blurred-image-1.jpg') %>">
          <%= nav_helper 'nav-link mx-1', 'span' %>
          <%= login_helper "nav-link" %>
          <%= nav_social_helper "d-lg-none d-xl-none" %>
      </div>
  </div>
</nav>