config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  resources :users, only: [:show]
  resources :messages, only: [:create]

  resources :posts do
    member do
      get :toggle_status
    end
  end

  get 'blog', to: 'pages#blog'

  mount ActionCable.server => '/cable'
  
  root to: 'pages#home'

end

app/views/pages/blog.html.erb
<div class="wrapper">
    <div class="page-header page-header-small">
        <div class="page-header-image" data-parallax="true" style="background-image: url('<%= image_path("bg24.jpg") %>') ;">
        </div>
        <div class="content-center">
            <div class="row">
                <div class="col-md-8 ml-auto mr-auto text-center">
                    <h2 class="title">The Blog</h2>
                </div>
            </div>
        </div>
    </div>
    <div class="main">
        <div class="blogs-3">
            <div class="container">
                <div class="row">
                    <div class="col-md-10 ml-auto mr-auto">
                        <h2 class="title">Latest Blogposts</h2>
                        <br />
                        <% @posts.each do |post| %>
                          <%= render 'posts/post_preview', post: post %>
                        <% end %>
                    </div>
                </div>
            </div>
        </div>

        <!-- <div class="subscribe-line subscribe-line-white">
            <div class="container">
                <div class="row">
                    <div class="col-md-6">
                        <h4 class="title">Get Tips &amp; Tricks every Week!</h4>
                        <p class="description">
                            Join our newsletter and get news in your inbox every week! We hate spam too, so no worries about this.
                        </p>
                    </div>
                    <div class="col-md-6">
                        <div class="card card-plain card-form-horizontal">
                            <div class="card-content">
                                <form method="" action="">
                                    <div class="row">
                                        <div class="col-sm-8">
                                            <div class="input-group">
                                                <div class="input-group-prepend">
                                                    <span class="input-group-text"><i class="now-ui-icons ui-1_email-85"></i></span>
                                                </div>
                                                <input type="text" class="form-control" placeholder="Email Address...">
                                            </div>
                                        </div>
                                        <div class="col-sm-4">
                                            <button type="button" class="btn btn-danger btn-round btn-block">Subscribe</button>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div> -->

    </div>
    <%= render 'shared/footer' %>
</div>

app/views/pages/home.html.erb
<div class="wrapper">
    <div class="page-header clear-filter" filter-color="red">
        <div class="page-header-image" data-parallax="true" style="background-image: url('<%= image_path("tim-home.png") %>');">
        </div>
        <div class="container">
            <div class="content-center brand">
                <h1><span class="title">Tim Pile</span> de·sign | /dəˈzīn/</h1>
                <h3>Thoughts about Life & Code</h3>
            </div>
        </div>
    </div>
    <div class="main">
        <div class="features-4">
            <div class="container">
                <div class="row">
                    <div class="col-md-8 ml-auto mr-auto text-center">
                        <h2 class="title">Welcome!</h2>
                        <h4 class="description">This site is my expression of curiousity & creativity. Here you'll find my thoughts and experiments in software, life hacking and philosophy.</h4>
                        <%= link_to "Go to Blog", blog_path, class: "btn btn-lg btn-default" %>
                    </div>
                </div>
            </div>
        </div>

        <div class="team-5 section-image" style="background-image: url('<%= image_path("bg4.jpg") %>');">
            <div class="container">
                <div class="row">
                    <div class="col-md-8 ml-auto mr-auto text-center">
                        <h2 class="title">About Tim</h2>
                        <h4 class="description">I've been writing software since 2011. The first 6 years of my career was in business intelligence, data management & analytics. I developed reporting software for enterprise sales, marketing, finance, and application usage statistics.</h4>
                        <h4 class="description">In 2016 I discovered Ruby on Rails for SaaS app development. It's ease of use and rapid prototyping make it my favorite language and framework to work with in the web.</h4>
                        <h4 class="description">When I'm not coding, I like hanging out with my wife Hannah and our two sweet golden retreivers, Hawker and Daisy. We love to run, travel and eat good food!</h4>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-4"></div>
                    <div class="col-md-4">
                        <div class="card card-profile">
                            <div class="card-avatar">
                                <%= image_tag("tim-profile.png", class: "img img-raised") %>
                            </div>
                            <div class="card-body">
                                <h4 class="card-title">Tim Pile</h4>
                                <h6 class="category text-danger">Software Engineer</h6>
                                <p class="card-description">
                                </p>
                                <div class="card-footer">
                                  <%= social_link_helper "btn btn-icon btn-neutral btn-round" %>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4"></div>
                </div>
            </div>
        </div>
        <%= render 'message_mailer/form' %>
      </div>
    <%= render 'shared/footer' %>
</div>