config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  resources :users, only: [:show]
  resources :messages, only: [:create]

  resources :posts do
    member do
      get :toggle_status
    end
  end

  get 'blog', to: 'pages#blog'

  mount ActionCable.server => '/cable'
  
  root to: 'pages#home'

end

app/models/post.rb
class Post < ApplicationRecord
  enum status: { draft: 0, published: 1}
  extend FriendlyId
  friendly_id :title, :use => :history

  mount_uploader :thumb_image, ImageUploader
  mount_uploader :main_image, ImageUploader

  belongs_to :user
  belongs_to :topic
  has_many :comments
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:show]
  before_action :set_post, only: [:show, :edit, :update, :destroy, :toggle_status]
  access all: [:show], site_admin: :all

  def index
    @posts = Post.order("created_at DESC")
  end

  def show
    if logged_in?(:site_admin) || @post.published?
      @post = Post.includes(:comments).friendly.find(params[:id])
      @comment = Comment.new

      @page_title = @post.title
      @seo_keywords = @post.title # add a field to model for keywords
    else
      redirect_to blog_path, notice: "You are not authorized to access this page."
    end
  end

  def new
    @post = Post.new
  end

  def edit
  end

  def create
    @post = Post.new(post_params)
    @post.user = current_user

    if @post.save
      redirect_to @post, notice: 'Post was successfully created.'
    else
      render :new
    end
  end

  def update
    if @post.update(post_params)
      redirect_to @post, notice: 'Post was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @post.destroy
    redirect_to posts_path, notice: 'Post was successfully destroyed.'
  end

  def toggle_status
    if @post.draft?
      @post.published!
    elsif @post.published?
      @post.draft!
    end
    redirect_to @post, notice: 'Post status has been updated.'
  end

  private
    def set_post
      @post = Post.friendly.find(params[:id])
    end

    def post_params
      params.require(:post).permit(:topic_id, :title, :body, :status, :main_image, :thumb_image)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
  class CodeRayify < Redcarpet::Render::HTML
    def block_code(code, language)
      CodeRay.scan(code, language).div
    end
  end

  def markdown(text)
    coderayified = CodeRayify.new(filter_html: true, hard_wrap: true)

    options = {
      fenced_code_blocks: true,
      no_entra_emphasis: true,
      autolink: true,
      lax_html_blocks: true,
      tables: true,
    }

    markdown_html = Redcarpet::Markdown.new(coderayified, options)
    markdown_html.render(text).html_safe
  end
end

app/views/posts/_admin_actions.html.erb
<% if logged_in?(:site_admin) %>
  <span class="mx-1"><%= link_to post.status.capitalize, toggle_status_post_path(post) %></span>
  | <span class="mx-1"><%= link_to "Edit", edit_post_path(post) %></span>
  | <span class="mx-1"><%= link_to "Delete", post, method: :delete, data: { confirm: "Are you sure you want to delete this post?" } %></span>
<% end %>

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |f| %>
  <div class="row">
      <div class="col-md-6">
          <div class="form-group">
              <%= f.label :title %>
              <%= f.text_field :title, id: :post_title, class: "form-control" %>
          </div>
      </div>
      <div class="col-md-3">
          <div class="form-group">
              <%= f.label :topic %>
              <%= f.select :topic_id, Topic.all.map { |t| [t.name, t.id] }, {}, { class: "selectpicker", data: { style: "btn btn-info btn-round" } } %>
          </div>
      </div>
      <div class="col-md-3">
          <div class="form-group">
              <%= f.label :status %>
              <%= f.select :status, Post.statuses.keys.map { |s| [s.humanize, s] }, {}, { class: "selectpicker", data: { style: "btn btn-info btn-round" } } %>
          </div>
      </div>
  </div>

  <div class="row">
      <div class="col-md-6">
      </div>
      <div class="col-md-3">
          <div class="form-group">
              <span class="btn btn-info btn-round btn-block btn-file">
                  <span id="main_image_text">Main Image</span> <input type="file">
                  <%= f.file_field :main_image, id: "post_main_image" %>
                  <%= f.hidden_field :main_image_cache %>
              </span>
          </div>
      </div>
      <div class="col-md-3">
          <div class="form-group">
              <span class="btn btn-info btn-round btn-block btn-file">
                  <span id="thumb_image_text">Thumb Image</span> <input type="file">
                  <%= f.file_field :thumb_image, id: "post_thumb_image" %>
                  <%= f.hidden_field :thumb_image_cache %>
              </span>
          </div>
      </div>
  </div>

  <div class="row">
      <div class="col-md-12">
          <div class="form-group">
              <%= f.label :body %>
              <%= f.text_area :body, id: :post_body, placeholder: "Blog post content", class: "form-control", rows: 15  %>
          </div>
      </div>
  </div>
  <%= f.submit "Save Post", class:"btn btn-info btn-fill btn-block" %>
<% end %>

app/views/posts/_post_info.html.erb
<div class="section section-blog-info">
    <div class="container">
        <div class="row">
            <div class="col-md-8 ml-auto mr-auto">
                <div class="row">
                    <!-- <div class="col-md-6">
                        <div class="blog-tags">
                            Tags:
                            <span class="label label-danger">Photography</span>
                            <span class="label label-danger">Stories</span>
                            <span class="label label-danger">Castle</span>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <a href="#pablo" class="btn btn-google btn-round pull-right">
                            <i class="fa fa-google"></i> 232
                        </a>
                        <a href="#pablo" class="btn btn-twitter btn-round pull-right">
                            <i class="fa fa-twitter"></i> 910
                        </a>
                        <a href="#pablo" class="btn btn-facebook btn-round pull-right">
                            <i class="fa fa-facebook-square"></i> 872
                        </a>
                    </div> -->
                </div>
                <hr />
                <div class="card card-profile card-plain">
                    <div class="row">
                        <div class="col-md-2">
                            <div class="card-avatar">
                                <a href="#pablo">
                                    <%= gravatar_helper post.user %>
                                </a>
                                <div class="ripple-container"></div>
                            </div>
                        </div>
                        <div class="col-md-8">
                            <h4 class="card-title"><%= post.user.name %></h4>
                        </div>
                        <div class="col-md-2">
                            <button type="button" class="btn btn-default pull-right btn-round">Follow</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/posts/_post_preview.html.erb
<div class="card card-plain card-blog">
    <div class="row">
        <div class="col-md-4">
            <div class="card-image">
                <%= image_tag(image_helper(post.thumb_image), class: "img img-raised rounded") %>
            </div>
        </div>
        <div class="col-md-8">
            <h4 class="card-title">
                <%= link_to post.title, post %>
            </h4>
            <p class="card-description">
                <%= markdown post.body[0..250] %>
                <%= link_to "Read More", post %>
            </p>
            <div class="author">
                <%= image_tag(image_helper(post.user.image), class: "avatar img-raised") %>
                <span><%= post.user.name %></span>
            </div>
        </div>
    </div>
</div>

app/views/posts/edit.html.erb
<div class="col-md-9">
    <div class="card">
          <div class="card-header">
              <div class="row">
                  <div class="col-md-6">
                      <h5 class="title">Edit Post</h5>
                  </div>
                  <div class="col-md-3">
                  </div>
                  <div class="col-md-3">
                  </div>
              </div>
          </div>
          <div class="card-body">
            <%= render 'form', post: @post %>
        </div>
    </div>
</div>
<div class="col-md-3">
    <div class="card card-user">
        <div class="card-body">
            <h5>Main Image </h5>
            <%= image_tag(image_helper(@post.main_image)) %>
            <h5>Thumb Image </h5>
            <%= image_tag(image_helper(@post.thumb_image)) %>
        </div>
    </div>
</div>

app/views/posts/index.html.erb
<div class="col-md-12">
    <div class="card">
        <div class="card-header">
            <h4 class="card-title pull-left">
              <%= fa_icon("feed") %> Posts
            </h4>
            <span class="pull-right"><%= link_to fa_icon("plus") + ' New Post'.html_safe, new_post_path, class: "btn btn-info" %> </span>
        </div>
        <div class="card-body">
            <table id="datatable" class="table table-striped table-bordered" cellspacing="0" width="100%">
                <thead>
                    <tr>
                        <th>Created</th>
                        <th>Title</th>
                        <th>Author</th>
                        <th>Status</th>
                        <th class="disabled-sorting text-right">Actions</th>
                    </tr>
                </thead>
                <tbody>
                  <% @posts.each do |post| %>
                    <tr>
                        <td><%= post.created_at.strftime("%Y-%m-%d") %></td>
                        <td><%= post.title %></td>
                        <td><%= post.user.name %></td>
                        <td><%= post.status %></td>
                        <td class="text-right">
                            <span><%= link_to fa_icon("arrow-circle-right"), post, class: "btn btn-round btn-info btn-icon btn-sm" %></span>
                            <span><%= link_to fa_icon("pencil"), edit_post_path(post), class: "btn btn-round btn-warning btn-icon btn-sm" %></span>
                            <span><%= link_to fa_icon("times"), post, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-round btn-danger btn-icon btn-sm remove" %></span>
                        </td>
                    </tr>
                  <% end %>
                </tbody>
            </table>
        </div>
        <!-- end content-->
    </div>
    <!--  end card  -->
</div>

app/views/posts/new.html.erb
<div class="col-md-9">
    <div class="card">
          <div class="card-header">
              <div class="row">
                  <div class="col-md-6">
                      <h5 class="title">New Post</h5>
                  </div>
                  <div class="col-md-3">
                  </div>
                  <div class="col-md-3">
                  </div>
              </div>
          </div>
          <div class="card-body">
            <%= render 'form', post: @post %>
        </div>
    </div>
</div>
<div class="col-md-3">
    <div class="card card-user">
        <div class="card-body">
        </div>
    </div>
</div>

app/views/posts/show.html.erb
<div class="wrapper">
    <div class="page-header page-header-small">
        <div class="page-header-image" data-parallax="true" style="background-image: url('<%= image_url(image_helper(@post.main_image)) %>')">
        </div>
    </div>
    <div class="section">
        <div class="container">
            <div class="row">
                <div class="col-md-8 ml-auto mr-auto">
                    <h2 class="title"><%= @post.title %></h2>
                    <nav class="breadcrumb">
                        <%= link_to "Home", root_path, class: 'breadcrumb-item' %>
                        <%= link_to "Blog", blog_path, class: 'breadcrumb-item' %>
                        <span class="breadcrumb-item active"><%= @post.title %></span>
                    </nav>
                    <span class="pull-right"><%= render 'posts/admin_actions', post: @post %></span>
                    Published <%= distance_of_time_in_words(@post.created_at, Time.current) %> ago
                    <p><%= markdown @post.body %></p>
                    <br>
                    <hr>
                </div>
            </div>
            <%#= render 'posts/post_info', post: @post %>
            <div class="row">
                <div class="col-md-8 ml-auto mr-auto">
                    <div class="media-area">
                        <h3 class="title text-center"><%= pluralize(@post.comments.count, 'Comment') %></h3>
                        <div class="media">
                            <div id="comments" data-post-id="<%= @post.id %>">
                                <%= render @post.comments %>
                            </div>
                        </div>
                    </div>
                    <%= render 'comments/comment_form', comment: @comment %>
                </div>
            </div>
        </div>
    </div>
    <%= render 'shared/footer' %>
</div>